#!/bin/bash

echo "0, 234" >>inputFile
echo "1, 98" >>inputFile
echo "2, 67" >>inputFile
echo "3, 24" >>inputFile
echo "4, 34" >>inputFile
echo "5, 54" >>inputFile
echo "6, 74" >>inputFile
echo "7, 83" >>inputFile
echo "8, 60" >>inputFile
echo "9, 45" >>inputFile
